# Generated by Django 3.1.7 on 2021-02-20 18:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crawler', '0002_config'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='news',
            options={'verbose_name': 'News'},
        ),
    ]
