# Generated by Django 3.1.7 on 2021-02-20 18:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crawler', '0003_auto_20210220_1820'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='news',
            options={'verbose_name_plural': 'News'},
        ),
    ]
