# Generated by Django 3.1.7 on 2021-02-20 18:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crawler', '0004_auto_20210220_1821'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='agency',
            options={'verbose_name_plural': 'Agencies'},
        ),
    ]
