# Generated by Django 3.1.7 on 2022-05-19 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crawler', '0005_auto_20210220_1822'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='token',
            field=models.CharField(max_length=64, null=True),
        ),
    ]
