# Generated by Django 3.1.7 on 2022-05-19 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crawler', '0006_news_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='token',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
