# Generated by Django 3.1.7 on 2022-05-19 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crawler', '0007_auto_20220519_1611'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='token',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
